apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "xfsc-orce.fullname" . }}-cr-leanea-com
  labels:
  {{- include "xfsc-orce.labels" . | nindent 4 }}
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"cr-leanea-com","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"do-block-storage"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
    volume.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.XORCE.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.XORCE.storageClass | quote }}
  volumeMode: Filesystem
  volumeName: pvc-1734b14e-e683-4c46-8a19-c0715c088621