apiVersion: v1
kind: Service
metadata:
  name: {{ include "xfsc-orce.fullname" . }}-cr-leanea-com
  labels:
  {{- include "xfsc-orce.labels" . | nindent 4 }}
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"cr-leanea-com","app.kubernetes.io/name":"cr-leanea-com","app.kubernetes.io/version":"3.0.2"},"name":"cr-leanea-com","namespace":"default"},"spec":{"ports":[{"name":"http","port":1880,"protocol":"TCP","targetPort":1880},{"name":"filebrowser","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app.kubernetes.io/instance":"cr-leanea-com","app.kubernetes.io/name":"cr-leanea-com"},"sessionAffinity":"None","type":"ClusterIP"}}
spec:
  type: {{ .Values.XORCE.type }}
  selector:
    app.kubernetes.io/instance: cr-leanea-com
    app.kubernetes.io/name: cr-leanea-com
  {{- include "xfsc-orce.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.XORCE.ports | toYaml | nindent 2 }}