#!/bin/bash
export KUBECONFIG=$2
#echo "Please enter the new hostname:"
#read NEW_HOSTNAME
NEW_HOSTNAME=$1
BASE_HOSTNAME=$1
NEW_HOSTNAME="$(echo "${NEW_HOSTNAME}" | tr '[:upper:]' '[:lower:]' | tr '.' '-')"
HOSTNAME=$NEW_HOSTNAME

echo "Deleting deployment, rsync-data-pod, and PVC for ${HOSTNAME}...PERCENTAGE10"

kubectl delete deployment "${HOSTNAME}"
kubectl delete pod "rsync-data-pod"
kubectl delete pvc "${HOSTNAME}"

echo "Deleted resources for ${HOSTNAME}."
/data/depgenerator/newkubescriptremover $BASE_HOSTNAME $2
