#!/bin/bash
export KUBECONFIG=$2
INGRESS_NAME="node-red-ingress"
NAMESPACE="default"
TLS_SECRET_NAME="leaneanew"

#echo "Enter the hostname:"
#read NEW_HOSTNAME
NEW_HOSTNAME=$1
SERVICE_NAME="$(echo "${NEW_HOSTNAME}" | tr '[:upper:]' '[:lower:]' | tr '.' '-')"
SERVICE_PORT="1880"

cat > service.yaml <<- EOM
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: $SERVICE_NAME
    app.kubernetes.io/name: $SERVICE_NAME
    app.kubernetes.io/version: 3.0.2
  name: $SERVICE_NAME
spec:
  ports:
  - name: http
    port: $SERVICE_PORT
    protocol: TCP
    targetPort: $SERVICE_PORT
  - name: filebrowser
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: $SERVICE_NAME
    app.kubernetes.io/name: $SERVICE_NAME
  sessionAffinity: None
  type: ClusterIP
EOM

kubectl apply -f service.yaml
rm service.yaml

# Add ingress rule
EXISTING_SERVICES=$(kubectl get ingress $INGRESS_NAME -n $NAMESPACE -o json | jq -r '.metadata.annotations."nginx.org/websocket-services" // ""')

if [[ $EXISTING_SERVICES == *"$SERVICE_NAME"* ]]; then
  UPDATED_SERVICES="$EXISTING_SERVICES"
else
  UPDATED_SERVICES="$EXISTING_SERVICES,$SERVICE_NAME"
fi

cat > add_host_patch.yaml <<- EOM
- op: add
  path: /spec/rules/-
  value:
    host: $NEW_HOSTNAME
    http:
      paths:
      - backend:
          service:
            name: $SERVICE_NAME
            port:
              number: $SERVICE_PORT
        path: /
        pathType: Prefix
      - backend:
          service:
            name: $SERVICE_NAME
            port:
              number: 80
        path: /fscloud
        pathType: Prefix
- op: add
  path: /spec/tls/-
  value:
    hosts:
    - $NEW_HOSTNAME
    secretName: $TLS_SECRET_NAME
EOM

kubectl patch ingress $INGRESS_NAME -n $NAMESPACE --type json --patch-file add_host_patch.yaml
rm add_host_patch.yaml

cat > update_annotation_patch.yaml <<- EOM
- op: replace
  path: /metadata/annotations/nginx.org~1websocket-services
  value: ${UPDATED_SERVICES#,}
EOM
echo "Getting things ready...PERCENTAGE98"
kubectl patch ingress $INGRESS_NAME -n $NAMESPACE --type json --patch-file update_annotation_patch.yaml

echo "PERCENTAGE100"
rm update_annotation_patch.yaml


