XORCE:
  filebrowser:
    args:
    - --baseurl
    - /fscloud
    image:
      repository: filebrowser/filebrowser
      tag: latest
    imagePullPolicy: Always
  xfscorceLeaneaCom:
    image:
      repository: leanea/xfsc-orce
      tag: 1.0.0
    imagePullPolicy: IfNotPresent
  ports:
  - name: http
    port: 1880
    protocol: TCP
    targetPort: 1880
  - name: filebrowser
    port: 80
    protocol: TCP
    targetPort: 80
  replicas: 1
  revisionHistoryLimit: 10
  type: ClusterIP
  volumePermissions:
    image:
      repository: busybox
      tag: latest
    imagePullPolicy: Always
kubernetesClusterDomain: cluster.local
pvc:
  XORCE:
    storageClass: do-block-storage
    storageRequest: 2Gi
ingress:
  name: node-red-ingress
  annotations:
    maxBodySize: "0"
    websocketServices: "cr-leanea-com"
  className: nginx
  host: cr-leanea.com
  tlsSecret: cr-leanea-com-tls

service:
  name: cr-leanea-com
  port: 1880
